name: "Hello world workflow"
# triggers the workflow on push done to master or production branch
on:
  push:
    branches:
      - main
      - production

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello word"
        run: echo "Hello world"

      - name: "Print current date"
        run: date
