name: My first workflow
on: [push, workflow_dispatch]
jobs:
  my-first-job: #job name
    runs-on: ubuntu-latest
    steps:
      - name: Print Node Version
        run: node --version
      - name: Install Nodejs version 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Print Node Version
        run: node --version
